WIP, ENH: control reduction types
* still a work in progress--this branch can compile
and run `02_simple_reduce.py` with the `pk.int64` type,
but somewhere in the control flow an overflow is
still happening for large values compared to NumPy

* `python runtests.py` passes 87 tests and fails 2
on this feature branch:
```
FAILED tests/test_lambdas.py::TestLambda::test_add - SystemExit: 1
FAILED tests/test_lambdas.py::TestLambda::test_add_squares - SystemExit: 1
```
- they look like type-related failures due to my crude initial
work here