core: update mypy and resolve issues (#428)
* Update mypy version

* Fix mypy typechecking for AST lineno

We were getting the mypy error
`pykokkos/core/translators/symbols_pass.py:192: error: "AST" has no
attribute "lineno"  [attr-defined]`
as not every AST object has a linenumber. To defend against this,
We now check if the `node` object has a `lineno` attribute,
and if not we return the value `'unknown'`.

* Resolve depreciation warning

```
/Users/kosmacher/miniconda3/envs/pyk/bin/mypy:11: DeprecationWarning: `numpy.typing.mypy_plugin` is deprecated, and will be removed in a future release. Please remove `plugins = numpy.typing.mypy_plugin` in your mypy config.(deprecated in NumPy 2.3)
  sys.exit(console_entry())
```